site_name: PredictionPerpsDocs
docs_dir: docs

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light

nav:
  - Home: FullReadMe/ReadMe.md
  - Overview:
      - What Is It?: FullReadMe/WhatIsIt.md
      - Technical Overview: FullReadMe/TechnicalReadMe.md

  - Accounting:
      - Standard Liquidity:
          - Ledger Overview: FullReadMe/Accounting/StandardLiquidity/LedgerOverview.md
          - Unified Liquidity: FullReadMe/Accounting/StandardLiquidity/UnifiedLiquidity.md
          - Ledger Accounting: FullReadMe/Accounting/StandardLiquidity/LedgerAccounting.md
      - Synthetic Liquidity:
          - Synthetic Overview: FullReadMe/Accounting/SyntheticLiquidity/SyntheticOverview.md
          - Synthetic Principles: FullReadMe/Accounting/SyntheticLiquidity/SyntheticPrinciples.md
          - Synthetic Accounting: FullReadMe/Accounting/SyntheticLiquidity/SyntheticAccounting.md
      - General:
          - Zero-Sum: FullReadMe/ZeroSum.md
          - Solvency (Concept): FullReadMe/Solvency.md
          - Solvency Accounting: FullReadMe/SolvencyAccounting.md
          - Heap Logic: FullReadMe/HeapLogic.md
  - Contracts:
      - Contracts Index: ContractsIndex.md
      - Core Contracts:
          - Ledger.sol: Contracts/Ledger.sol.md
          - AMM.sol: Contracts/AMM.sol.md
          - PositionToken1155.sol: Contracts/PositionToken1155.sol.md
      - Interfaces:
          - IERC20Permit.sol: Contracts/IERC20Permit.sol.md
          - ILedger.sol: Contracts/ILedger.sol.md
          - IPermit2.sol: Contracts/IPermit2.sol.md
          - iPositionToken1155.sol: Contracts/iPositionToken1155.sol.md
      - Libraries:
          - AllocateCapitalLib.sol: Contracts/Libraries/AllocateCapitalLib.sol.md
          - DepositWithdrawLib.sol: Contracts/Libraries/DepositWithdrawLib.sol.md
          - HeapLib.sol: Contracts/Libraries/HeapLib.sol.md
          - LedgerLib.sol: Contracts/Libraries/LedgerLib.sol.md
          - LiquidityLib.sol: Contracts/Libraries/LiquidityLib.sol.md
          - MarketManagementLib.sol: Contracts/Libraries/MarketManagementLib.sol.md
          - RedemptionLib.sol: Contracts/Libraries/RedemptionLib.sol.md
          - SolvencyLib.sol: Contracts/Libraries/SolvencyLib.sol.md
          - StorageLib.sol: Contracts/Libraries/StorageLib.sol.md
          - TokenOpsLib.sol: Contracts/Libraries/TokenOpsLib.sol.md
          - TradingLib.sol: Contracts/Libraries/TradingLib.sol.md
          - Types.sol: Contracts/Libraries/Types.sol.md
          - TypesPermit.sol: Contracts/Libraries/TypesPermit.sol.md
  - Pitch: Pitch.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      extend_pygments_lang:
        - name: solidity
          lang: solidity
          aliases: [sol]
          lexer: mysolidity
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2-6

plugins:
  - search
  - mermaid2:
      version: "10.9.1"

extra_css:
  - stylesheets/extra.css
  - stylesheets/solidity.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
