site_name: PredictionPerpsDocs
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light

nav:
  - ReadMe: index.md
  - Documents Needed: DocumentsNeeded.md
  - NonTechnical:
      - Short Pitch: NonTechnical/ShortPitch.md
      - What Is It?: NonTechnical/WhatIsIt.md
  - Technical:
      - Technical ReadMe: Technical/TechnicalReadMe.md
      - Prediction Perps Whitepaper: Technical/PredictionPerpsWhitepaper.md
      - 1 Ledger:
          - Ledger ReadMe: Technical/1 Ledger/LedgerReadMe.md
          - Ledger Whitepaper: Technical/1 Ledger/LedgerWhitepaper.md
          - Ledger Technical Docs:
              - Ledger Expanding Markets: Technical/1 Ledger/LedgerTechinalDocs/LedgerExpandingMarkets.md
              - Ledger Zero-Sum: Technical/1 Ledger/LedgerTechinalDocs/LedgerZeroSum.md
              - Solvency:
                  - Solvency Accounting: Technical/1 Ledger/LedgerTechinalDocs/Solvency/SolvencyAccounting.md
                  - Solvency Overview: Technical/1 Ledger/LedgerTechinalDocs/Solvency/SolvencyOverview.md
              - Standard Liquidity:
                  - Heap Logic: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/HeapLogic.md
                  - Ledger Overview: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/LedgerOverview.md
                  - Standard Ledger Accounting: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/StandardLedgerAccounting.md
                  - Unified Liquidity Discussion: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/UnifiedLiquidityDiscussion.md
              - Synthetic Liquidity:
                  - Synthetic Liquidity Accounting: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticLiquidityAccounting.md
                  - Synthetic Liquidity Overview: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticLiquidityOverview.md
                  - Synthetic Liquidity Principles: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticLiquidityPrinciples.md
      - 2 LMSR:
          - LMSR ReadMe: Technical/2 LMSR/LMSRReadMe.md
          - PP LMSR Whitepaper: Technical/2 LMSR/PPLMSRWhitepaper.md
          - LMSR Technical Docs:
              - LMSR Expansion Maths: Technical/2 LMSR/LMSRTechnicalDocs/LMSRExpansionMaths.md
              - LMSR Initialisation Storage: Technical/2 LMSR/LMSRTechnicalDocs/LMSRInitialisationStorage.md
              - LMSR Marginal Prices: Technical/2 LMSR/LMSRTechnicalDocs/LMSRMarginalPrices.md
              - LMSR Quotes: Technical/2 LMSR/LMSRTechnicalDocs/LMSRQuotes.md
              - LMSR State Changes: Technical/2 LMSR/LMSRTechnicalDocs/LMSRStateChanges.md
              - LMSR Weight Variables Defined: Technical/2 LMSR/LMSRTechnicalDocs/LMSRWeightVariablesDefined.md
      - 3 Tokens:
          - Token Naming: Technical/3 Tokens/TokenNaming.md
      - 4 Unified Flows:
          - Full Contract Deployment: Technical/4 Unified Flows/FullContractDeployment.md
          - Full Market Intialisation: Technical/4 Unified Flows/FullMarketIntialisation.md
          - Full Purchase Tokens: Technical/4 Unified Flows/FullPurchaseTokens.md
          - Fruit Market Examples:
              - Fruit Market Initialisation: Technical/4 Unified Flows/Fruit Market Examples/FruitMarketInitialisation.md
              - Fruit Market Price Changes: Technical/4 Unified Flows/Fruit Market Examples/FruitMarketPriceChanges.md
      - 5 Appendices:
          - Contracts Index: Technical/5 Appendices/ContractsIndex.md
          - Glossary: Technical/5 Appendices/Glossary.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: false
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      extend_pygments_lang:
        - name: solidity
          lang: solidity
          aliases: [sol]
          lexer: mysolidity
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2-6
  - meta

plugins:
  - search
  - mermaid2:
      version: "10.9.1"
      arguments:
        securityLevel: 'loose'
  - awesome-pages  # New: Enables frontmatter slugs for URLs

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/extra.js