site_name: PredictionPerpsDocs
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light

nav:
  - ReadMe: index.md
  - Documents Needed: DocumentsNeeded.md
  - NonTechnical:
      - Pitch: NonTechnical/Pitch.md
      - What Is It?: NonTechnical/WhatIsIt.md
  - Technical:
      - Technical ReadMe: Technical/TechnicalReadMe.md
      - Prediction Perps Whitepaper: Technical/PredictionPerpsWhitepaper.md
      - 1 Ledger:
          - Ledger ReadMe: Technical/1 Ledger/LedgerReadMe.md
          - Ledger Whitepaper: Technical/1 Ledger/LedgerWhitepaper.md
          - Ledger Technical Docs:
              - Ledger Expanding Markets: Technical/1 Ledger/LedgerTechinalDocs/LedgerExpandingMarkets.md
              - Solvency:
                  - Solvency: Technical/1 Ledger/LedgerTechinalDocs/Solvency/Solvency.md
                  - Solvency Accounting: Technical/1 Ledger/LedgerTechinalDocs/Solvency/SolvencyAccounting.md
              - Standard Liquidity:
                  - Heap Logic: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/HeapLogic.md
                  - Ledger Accounting: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/LedgerAccounting.md
                  - Ledger Overview: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/LedgerOverview.md
                  - Unified Liquidity: Technical/1 Ledger/LedgerTechinalDocs/StandardLiquidity/UnifiedLiquidity.md
              - Synthetic Liquidity:
                  - Synthetic Accounting: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticAccounting.md
                  - Synthetic Overview: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticOverview.md
                  - Synthetic Principles: Technical/1 Ledger/LedgerTechinalDocs/SyntheticLiquidity/SyntheticPrinciples.md
              - Zero-Sum: Technical/1 Ledger/LedgerTechinalDocs/ZeroSum.md
      - 2 LMSR:
          - LMSR ReadMe: Technical/2 LMSR/LMSRReadMe.md
          - PP LMSR Whitepaper: Technical/2 LMSR/PPLMSRWhitepaper.md
          - LMSR Technical Docs:
              - Initialisation Storage: Technical/2 LMSR/LMSRTechnicalDocs/InitialisationStorage.md
              - LMSR Expansion New Position LMSR Maths: Technical/2 LMSR/LMSRTechnicalDocs/LMSRExpansionNewPositionLMSRMaths.md
              - Market Pricing: Technical/2 LMSR/LMSRTechnicalDocs/MarketPricing.md
              - Quote: Technical/2 LMSR/LMSRTechnicalDocs/Quote.md
              - State Changes: Technical/2 LMSR/LMSRTechnicalDocs/StateChanges.md
              - Weight Variables: Technical/2 LMSR/LMSRTechnicalDocs/WeightVariables.md
      - 3 Tokens:
          - Token Names: Technical/3 Tokens/TokenNames.md
      - 4 Unified Flows:
          - Contract Deployment: Technical/4 Unified Flows/ContractDeployment.md
          - Market Initialisation: Technical/4 Unified Flows/MarketIntialisation.md
          - Token Purchase Flow: Technical/4 Unified Flows/PurchaseToken.md
          - Fruit Market Examples:
              - Market Initialisation: Technical/4 Unified Flows/Fruit Market Examples/MarketInitialisation.md
              - Price Changes: Technical/4 Unified Flows/Fruit Market Examples/PriceChanges.md
              - WIP Pricing Walkthrough: Technical/4 Unified Flows/Fruit Market Examples/WIPPricingWalkthrough.md
      - 5 Appendices:
          - Contracts Index: Technical/5 Appendices/ContractsIndex.md
          - Glossary: Technical/5 Appendices/Glossary.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: false
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      extend_pygments_lang:
        - name: solidity
          lang: solidity
          aliases: [sol]
          lexer: mysolidity
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2-6
  - meta

plugins:
  - search
  - mermaid2:
      version: "10.9.1"
      arguments:
        securityLevel: 'loose'
  - awesome-pages  # New: Enables frontmatter slugs for URLs

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/extra.js