site_name: PredictionPerpsDocs
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light

nav:
  - ReadMe: index.md
  - Overview:
      - What Is It?: FullReadMe/WhatIsIt.md
      - Technical Overview: FullReadMe/TechnicalReadMe.md
      - Documents Still Needed: FullReadMe/DocumentsNeeded.md

  - Accounting:
      - Standard Liquidity:
          - Ledger Overview: FullReadMe/Accounting/StandardLiquidity/LedgerOverview.md
          - Unified Liquidity: FullReadMe/Accounting/StandardLiquidity/UnifiedLiquidity.md
          - Ledger Accounting: FullReadMe/Accounting/StandardLiquidity/LedgerAccounting.md
      - Synthetic Liquidity:
          - Synthetic Overview: FullReadMe/Accounting/SyntheticLiquidity/SyntheticOverview.md
          - Synthetic Principles: FullReadMe/Accounting/SyntheticLiquidity/SyntheticPrinciples.md
          - Synthetic Accounting: FullReadMe/Accounting/SyntheticLiquidity/SyntheticAccounting.md
      - General:
          - Zero-Sum: FullReadMe/ZeroSum.md
          - Solvency (Concept): FullReadMe/Solvency.md
          - Solvency Accounting: FullReadMe/SolvencyAccounting.md
          - Heap Logic: FullReadMe/HeapLogic.md
  - Flows:
      - Contract Deployment: Flows/ContractDeployment.md
      - Market Initialisation: Flows/MarketInitialisation.md
      - Token Names: Flows/TokenNames.md
      - Purchase Flow:
        - Purchase Flow Overview: Flows/PurchaseToken/PurchaseFlowOverview
        - Purchase Flow Front End: Flows/PurchaseToken/PurchaseFlowFrontEnd
        - Purchase Flow LMSR: Flows/PurchaseToken/PurchaseFlowLMSR
        - Purchase Flow Ledger: Flows/PurchaseToken/PurchaseFlowLedger

  - Pricing: FullReadMe/AMM.md
  - Contracts Index: ContractsIndex.md
  - Pitch: Pitch.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: false
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      extend_pygments_lang:
        - name: solidity
          lang: solidity
          aliases: [sol]
          lexer: mysolidity
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2-6
  - meta

plugins:
  - search
  - mermaid2:
      version: "10.9.1"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/extra.js